## Financial News Sentiment Analysis

### Libraries

In [16]:
# import libraries
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..'))) # Adding racine path of project to sys.path
import pandas as pd
import datetime
import warnings
from src.preprocessing import * # Module created

warnings.filterwarnings('ignore')

### Import data and preprocessing

In [ ]:
df = wrangle('../data/raw_analyst_ratings.csv') #Preprocessing function defined in src module
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 1407327 entries, 0 to 1407327
Data columns (total 5 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   headline   1407327 non-null  str
 1   url        1407327 non-null  str
 2   publisher  1407327 non-null  str
 3   date       1407327 non-null  datetime64[us, UTC]
 4   stock      1407327 non-null  str
dtypes: datetime64[us, UTC](1), str(4)
memory usage: 64.4 MB

,headline,url,publisher,date,stock
0,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 14:30:54+00:00,A
1,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 14:45:20+00:00,A
2,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 08:30:07+00:00,A
3,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 16:45:06+00:00,A
4,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 15:38:59+00:00,A

### Exploratory Data Analysis

#### Descriptive statistics

In [ ]:
# Headline length
df["headline_length"] = df["headline"].apply(lambda i: len(i))
df.head()

,headline,url,publisher,date,stock,headline_length
0,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 14:30:54+00:00,A,39
1,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 14:45:20+00:00,A,42
2,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 08:30:07+00:00,A,29
3,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 16:45:06+00:00,A,44
4,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 15:38:59+00:00,A,87

In [10]:
trial = df[["headline","publisher"]]
trial.head()

                                            headline          publisher
0            Stocks That Hit 52-Week Highs On Friday  Benzinga Insights
1         Stocks That Hit 52-Week Highs On Wednesday  Benzinga Insights
2                      71 Biggest Movers From Friday         Lisa Levin
3       46 Stocks Moving In Friday's Mid-Day Session         Lisa Levin
4  B of A Securities Maintains Neutral on Agilent...         Vick Meyer

In [13]:
trial.drop_duplicates(inplace=True)

In [14]:
trial["publisher"].groupby(trial["publisher"]).count()

publisher
47ertrends                        2
AARP                              2
ABNNewswire                      10
Aakin                             4
Aaron Jackson.Ed                  6
                              ...
vic@forextraininggroup.com        1
vishwanath@benzinga.com        1830
vivek.proactive@gmail.com       120
wallstreet1928                    8
webmaster                     13668
Name: publisher, Length: 1034, dtype: int64